# Generated by Django 5.2.8 on 2026-04-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='category',
            field=models.CharField(choices=[('palace', 'Palace'), ('temple', 'Temple'), ('museum', 'Museum'), ('nature', 'Nature')], default='palace', max_length=20),
        ),
    ]
