# Generated by Django 5.2.8 on 2026-02-24 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_alter_photo_caption_alter_photo_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='place',
            field=models.CharField(max_length=100),
        ),
    ]
